### ISSUE TITLE
What exactly is this project about?

### ISSUE THREAD

**Issue by dan-m8t** [okd-project/okd-scos#2]
Hi there,

sorry to open an issue, cannot open a discussion here though.

I want to know what exactly is this project to be meant, especially in comparison to OKD.

I watched a YouTube video that explained that the underlying operating system will be closer attached to RHCOS (like CentOS Stream to RHEL). But does that also change the OKD components? Like the components are derived from OCP and will act as something like a "OKD Stream" which is ahead of OCP but more stable than OKD on FCOS? 

And will it be possible to upgrade from FCOS OKD release channel to OKD SCOS release channel or is it necessary to reinstall the whole cluster because it is kind of a different OS?

Looking forward to hear from you :)

Thanks

Dan

**Comment by vrutkovs** [comment]
My take on this (hopefully more opinions will follow):
>I want to know what exactly is this project to be meant, especially in comparison to OKD.

Same as OKD, but uses CentOS instead of FCOS. The benefit is CentOS Stream kernel, the downside is slower fix pace.

>Like the components are derived from OCP and will act as something like a "OKD Stream" which is ahead of OCP but more stable than OKD on FCOS?

I'd prefer not to. We already had "OKD as OCP upstream" and it didn't end well for both parties. We do want to release stable builds earlier than OCP builds land in stable channel though.

>And will it be possible to upgrade from FCOS OKD release channel to OKD SCOS release channel or is it necessary to reinstall the whole cluster because it is kind of a different OS?

It should be possible to upgrade in both directions - rpm-ostree and operators allow us to change the contents effortlessly. I'm concerned about bootloader bits which may backfire later on (this is something we'd need to look into as part of OpenShift upgrade story).

**Comment by dmueller2001** [comment]
A bit more background on the OKD Streams initiative & MVP OKD on SCOS release here: https://www.okd.io/blog/2022-10-25-OKD-Streams-Building-the-Next-Generation-of-OKD-together/

**Comment by travier** [comment]
Closing as there is nothing to do here beside maybe adding some links to the README.
