### ISSUE TITLE
4.12.0-0.okd-scos-2022-10-25-053756 create cluster errors systemd-sysusers.service FAILURE

### ISSUE THREAD

**Issue by apmlima** [okd-project/okd-scos#4]
Hi guys,
When creating the cluster on AWS I get the following error:
level=error msg="Cluster operator authentication Degraded is True with IngressStateEndpoints_MissingSubsets::OAuthServerServiceEndpointAccessibleController_SyncError::OAuthServerServiceEndpointsEndpointAccessibleController_SyncError: IngressStateEndpointsDegraded: No subsets found for the endpoints of oauth-server\nOAuthServerServiceEndpointAccessibleControllerDegraded: Get \"https://172.30.93.151:443/healthz\": dial tcp 172.30.93.151:443: connect: connection refused\nOAuthServerServiceEndpointsEndpointAccessibleControllerDegraded: oauth service endpoints are not ready"

Also found the following on the log bundle:
systemd-sysusers[786]: Creating user 'systemd-oom' (systemd Userspace OOM Killer) with UID 990 and GID 990.
systemd-sysusers[786]: /etc/gshadow: Group "sgx" already exists.
systemd-sysusers[786]: Failed to write files: File exists
systemd[1]: systemd-sysusers.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: systemd-sysusers.service: Failed with result 'exit-code'.
systemd[1]: Failed to start Create System Users.

On latest 4.11 everything is working fine.
Can you please advise?

Pedro

**Comment by LorbusChris** [comment]
Thanks for the report.
There are two things here:
- The sysusers error is known but so far does not seems to cause problems. It's probably due to rebasingfrom FCOS to SCOS during install. 

- The oauth-related failure is due to instabilities with that code in the 4.12 snapshot it was built from. You could retry your install in this case, it shouldn't happen every time.
We'll cut another 4.12 pre-release shortly with improved stability too in case you prefer that.

**Comment by apmlima** [comment]
Thanks @LorbusChris for the feedback.
I'll wait for that newer 4.12-scos.
